name: Build pandepth image

on:
  push:
    paths:
      - 'images/pandepth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: images/pandepth/Dockerfile
          build-args: MODULE_VERSION=2.26
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pandepth:2.26
            ghcr.io/${{ github.repository_owner }}/pandepth:latest
